name: pahomqtt
description: Paho MQTT 是由 Eclipse 开发的一套基于 MQTT 协议的客户端程序。
keywords:
  - MQTT
  - IoT
  - Network
author:
  name: Dave Gamble (original author), Max Bruckner (current maintainer)
license: MIT                                   # GPLv2，LGPLv2.1，MIT，Apache license v2.0，BSD

depends:                                       # 该组件依赖其他的组件
  - libc

source_file:
  - "MQTTPacket/*.c"
  - "MQTTClient/*.cxx"

build_config:
  include:
    - MQTTPacket
  cflag: ""                             # C 编译器所需要要的编译参数

install:
  - dest: "include/"
    source:
      - MQTTPacket/MQTTPacket.h
